name: Build and Publish Spring Boot App

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Upload Geoweaver Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: geoweaver-artifacts
        path: |
          target/*.war
          target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Geoweaver Artifacts
      uses: actions/download-artifact@v2
      with:
        name: geoweaver-artifacts

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Description of the release
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload WAR Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./geoweaver-artifacts/geoweaver.war
        asset_name: geoweaver.war
        asset_content_type: application/zip

    - name: Upload JAR Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./geoweaver-artifacts/geoweaver.jar
        asset_name: geoweaver.jar
        asset_content_type: application/zip
